# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586c141e0f8341655753ba8813cc042dd800dc8642d2844ced62a35ab92548f9b532370df09ac51e4391fd1fc43083f0c36f69a05af5a054d476d2cb4f5eb94d

test:
  secret_key_base: 678d3c90cbbb1e075109e8cd84e4c0dcbda9333957f87749f89fc91f2eb168315db4ed9c0a19ecf43ef45a55a83bcfbc88eaf5691bd6021a8902dffc94176e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
